### ISSUE TITLE
Have error "Message data too large. Enable debug if asked to do so" so how to fix it?

### ISSUE THREAD

**Issue by banhao** [CiscoSecurity/fp-05-microsoft-sentinel-connector#2]
[root@prov-s-5046 eNcore]# ./encore.sh foreground
2021-07-06 17:59:13,549 Controller   INFO     eNcore version: development
2021-07-06 17:59:13,549 Controller   INFO     Python version: 2.7.17 (default, Aug 18 2020, 09:42:29) \n[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
2021-07-06 17:59:13,550 Controller   INFO     Platform version: Linux-4.18.0-240.22.1.el8_3.x86_64-x86_64-with-redhat-8.3-Ootpa
2021-07-06 17:59:13,550 Controller   INFO     Starting client (pid=284191).
2021-07-06 17:59:13,550 Controller   INFO     Sha256: 742739f29fb569164627c7171d750f9e6d1cab888f4cecfd19c11f20c34474f7
2021-07-06 17:59:13,550 Controller   INFO     Processes: 4
2021-07-06 17:59:13,550 Controller   INFO     Settings: KGRwMApWYWx3YXlzQXR0ZW1wdFRvQ29udGludWUKcDEKSTAxCnNWbG9nZ2luZwpwMgooZHAzClZsZXZAY29tbWVudApwNApWTGV2ZWxzIGluY2x1ZGUgRkFUQUwsIEVSUk9SLCBXQVJOSU5HLCBJTkZPLCBERUJVRywgVkVSQk9TRSBhbmQgVFJBQ0UKcDUKc1ZsZXZlbApwNgpWSU5GTwpwNwpzVmZvcm1hdApwOApWJShhc2N0aW1lKXMgJShuYW1lKS0xMnMgJShsZXZlbG5hbWUpLThzICUobWVzc2FnZSlzCnA5CnNWc3RkT3V0CnAxMApJMDEKc1ZmaWxlcGF0aApwMTEKVmVzdHJlYW1lci5sb2cKcDEyCnNzVmNvbm5lY3RUaW1lb3V0CnAxMwpJMTAKc1ZzdGFyQGNvbW1lbnQKcDE0ClYwIGZvciBnZW5lc2lzLCAxIGZvciBub3csIDIgZm9yIGJvb2ttYXJrCnAxNQpzVmVuYWJsZWQKcDE2CkkwMQpzVndvcmtlclByb2Nlc3NlcwpwMTcKSTQKc1ZzdGFydApwMTgKSTEKc1ZoYW5kbGVyCnAxOQooZHAyMApWb3V0cHV0dGVycwpwMjEKKGxwMjIKKGRwMjMKVmFkYXB0ZXIKcDI0ClZqc29uCnAyNQpzVmVuYWJsZWQKcDI2CkkwMQpzVnN0cmVhbQpwMjcKKGRwMjgKVm9wdGlvbnMKcDI5CihkcDMwClZtYXhMb2dzCnAzMQpJMTAwMDAKc1Zyb3RhdGUKcDMyCkkwMQpzc1Z1cmkKcDMzClZyZWxmaWxlOi8vL2RhdGEvanNvbi9lbmNvcmUuezB9LmxvZwpwMzQKc3NhKGRwMzUKVmFkYXB0ZXIKcDM2ClZjZWYKcDM3CnNWZW5hYmxlZApwMzgKSTAxCnNWbmFtZQpwMzkKVkNFRlNlbnRpbmVsCnA0MApzVnN0cmVhbQpwNDEKKGRwNDIKVnVyaQpwNDMKVnRjcDovLzEyNy4wLjAuMToyNTIyNgpwNDQKc3Nhc1ZvdXRwdXRAY29tbWVudApwNDUKVklmIHlvdSBkaXNhYmxlIGFsbCBvdXRwdXR0ZXJzIGl0IGJlaGF2ZXMgYXMgYSBzaW5rCnA0NgpzVnJlY29yZHMKcDQ3CihkcDQ4ClZjb3JlCnA0OQpJMDEKc1ZpbnRydXNpb24KcDUwCkkwMQpzVmluY0Bjb21tZW50CnA1MQpWVGhlc2UgcmVjb3JkcyB3aWxsIGJlIGluY2x1ZGVkIHJlZ2FyZGxlc3Mgb2YgYWJvdmUKcDUyCnNWcm5hCnA1MwpJMDEKc1ZydWEKcDU0CkkwMQpzVnBhY2tldHMKcDU1CkkwMQpzVmNvbm5lY3Rpb25zCnA1NgpJMDEKc1ZleGNsdWRlCnA1NwoobHA1OApzVmluY2x1ZGUKcDU5CihscDYwCnNWZXhjbEBjb21tZW50CnA2MQoobHA2MgpWVGhlc2UgcmVjb3JkcyB3aWxsIGJlIGV4Y2x1ZGVkIHJlZ2FyZGxlc3Mgb2YgYWJvdmUgKG92ZXJyaWRlcyAnaW5jbHVkZScpCnA2MwphVmUuZy4gdG8gZXhjbHVkZSBmbG93IGFuZCBJUFMgZXZlbnRzIHVzZSBbIDcxLCA0MDAgXQpwNjQKYXNWbWV0YWRhdGEKcDY1CkkwMQpzc3NWcmVzcG9uc2VUaW1lb3V0CnA2NgpJMgpzVnN1YnNjcmlwdGlvbgpwNjcKKGRwNjgKVnJlY29yZHMKcDY5CihkcDcwClZleHRlbmRlZApwNzEKSTAxCnNWYXJjaGl2ZVRpbWVzdGFtcHMKcDcyCkkwMQpzVmludHJ1c2lvbgpwNzMKSTAxCnNWcGFja2V0RGF0YQpwNzQKSTAxCnNWQGNvbW1lbnQKcDc1CihscDc2ClZKdXN0IGJlY2F1c2Ugd2Ugc3Vic2NyaWJlIGRvZXNuJ3QgbWVhbiB0aGUgc2VydmVyIGlzIHNlbmRpbmcuIE5vciBkb2VzIGl0IG1lYW4KcDc3CmFWd2UgYXJlIHdyaXRpbmcgdGhlIHJlY29yZHMgZWl0aGVyLiBTZWUgaGFuZGxlci5yZWNvcmRzW10KcDc4CmFzVmV2ZW50RXh0cmFEYXRhCnA3OQpJMDEKc1ZpbXBhY3RFdmVudEFsZXJ0cwpwODAKSTAxCnNWbWV0YWRhdGEKcDgxCkkwMQpzc1ZzZXJ2ZXJzCnA4MgoobHA4MwooZHA4NApWcGtjczEyRmlsZXBhdGgKcDg1ClZjbGllbnQucGtjczEyCnA4NgpzVmhvc3QKcDg3ClYxNzIuMzAuMjA0LjgKcDg4CnNWdGxzVmVyc2lvbgpwODkKRjEuMApzVnBvcnQKcDkwCkk4MzAyCnNWdGxzQGNvbW1lbnQKcDkxClZWYWxpZCB2YWx1ZXMgYXJlIDEuMCBhbmQgMS4yCnA5MgpzYXNzVm1vbml0b3IKcDkzCihkcDk0ClZib29rbWFyawpwOTUKSTAwCnNWdmVsb2NpdHkKcDk2CkkwMApzVmhhbmRsZWQKcDk3CkkwMQpzVnN1YnNjcmliZWQKcDk4CkkwMQpzVnBlcmlvZApwOTkKSTEyMApzcy4=
2021-07-06 17:59:13,550 Diagnostics  INFO     Check certificate
2021-07-06 17:59:13,551 Diagnostics  INFO     Creating connection
2021-07-06 17:59:13,551 Connection   INFO     Connecting to 172.30.204.8:8302
2021-07-06 17:59:13,551 Connection   INFO     Using TLS v1.0
2021-07-06 17:59:13,592 Diagnostics  INFO     Creating request message
2021-07-06 17:59:13,592 Diagnostics  INFO     Request message=0001000200000008ffffffff48900061
2021-07-06 17:59:13,592 Diagnostics  INFO     Sending request message
2021-07-06 17:59:13,592 Diagnostics  INFO     Receiving response message
2021-07-06 17:59:13,618 Diagnostics  INFO     Response message=KGRwMApTJ2xlbmd0aCcKcDEKSTQ4CnNTJ3ZlcnNpb24nCnAyCkkxCnNTJ2RhdGEnCnAzClMnXHgwMFx4MDBceDEzXHg4OVx4MDBceDAwXHgwMFx4MDhceDAwXHgwMFx4MDBceDAwXHgwMFx4MDBceDAwXHgwMFx4MDBceDAwXHgxM1x4ODhceDAwXHgwMFx4MDBceDA4XHgwMFx4MDBceDAwXHgwMFx4MDBceDAwXHgwMFx4MDBceDAwXHgwMFx4MWFceDBiXHgwMFx4MDBceDAwXHgwOFx4MDBceDAwXHgwMFx4MDBceDAwXHgwMFx4MDBceDAwJwpwNApzUydtZXNzYWdlVHlwZScKcDUKSTIwNTEKcy4=
2021-07-06 17:59:13,619 Diagnostics  INFO     Streaming info response
2021-07-06 17:59:13,619 Diagnostics  INFO     Connection successful
2021-07-06 17:59:13,619 Monitor      INFO     Starting Monitor.
2021-07-06 17:59:13,629 Transformer  INFO     Starting process.
2021-07-06 17:59:13,629 Writer       INFO     Starting process.
2021-07-06 17:59:13,629 Monitor      INFO     Starting. 0 handled; average rate 0 ev/sec;
2021-07-06 17:59:13,635 Connection   INFO     Connecting to 172.30.204.8:8302
2021-07-06 17:59:13,635 Connection   INFO     Using TLS v1.0
2021-07-06 17:59:13,635 Decorator    INFO     Starting process.
2021-07-06 17:59:14,089 Settings     INFO     Timestamp: Start = 1 (Current data)
2021-07-06 17:59:14,089 Receiver     INFO     EventStreamRequestMessage: 0001000200000008ffffffff48900061
2021-07-06 17:59:14,089 SubscriberParser INFO     Starting process.
2021-07-06 17:59:14,100 Settings     INFO     Timestamp: Start = 1 (Current data)
2021-07-06 17:59:14,101 Receiver     INFO     StreamingRequestMessage: 000108010000003800001a0b0000003848900061ffffffff0009000c000400150009001f000b003d000e00470004005b000700650006006f0002008300000000
2021-07-06 17:59:17,915 Cache        INFO     Loading cache from /opt/app/eNcore/172.30.204.8-8302_cache.dat
2021-07-06 17:59:17,915 Cache        INFO     Cache file "/opt/app/eNcore/172.30.204.8-8302_cache.dat" does not exist. Using default values
2021-07-06 17:59:19,358 Bookmark     INFO     Bookmark file /opt/app/eNcore/172.30.204.8-8302_bookmark.dat does not exist.
2021-07-06 17:59:19,363 Writer       ERROR    error: \nTraceback (most recent call last):\n  File "/opt/app/eNcore/estreamer/baseproc.py", line 208, in receiveInput\n    self.onReceive( item )\n  File "/opt/app/eNcore/estreamer/baseproc.py", line 313, in onReceive\n    self.onEvent( item )\n  File "/opt/app/eNcore/estreamer/pipeline.py", line 413, in onEvent\n    write( item, self.settings )\n  File "/opt/app/eNcore/estreamer/pipeline.py", line 235, in write\n    streams[ index ].write( event['payloads'][index] + delimiter )\n  File "/opt/app/eNcore/estreamer/streams/tcp.py", line 52, in write\n    self.__connect()\n  File "/opt/app/eNcore/estreamer/streams/tcp.py", line 36, in __connect\n    self.socket.connect( ( self.host, self.port) )\n  File "/usr/lib64/python2.7/socket.py", line 228, in meth\n    return getattr(self._sock,name)(*args)\nerror: [Errno 111] Connection refused\n
2021-07-06 17:59:19,363 Writer       ERROR    Message data too large. Enable debug if asked to do so.
2021-07-06 17:59:19,363 Writer       INFO     Error state. Clearing queue

**Comment by banhao** [comment]
My test is successful:

[root@prov-s-5046 eNcore]# ./encore.sh test
2021-07-07T08:11:38.852518 Diagnostics  INFO    Checking that configFilepath (estreamer.conf) exists
2021-07-07 08:11:38,858 Diagnostics  INFO     Check certificate
2021-07-07 08:11:38,860 Diagnostics  INFO     Creating connection
2021-07-07 08:11:38,860 Connection   INFO     Connecting to 172.30.204.8:8302
2021-07-07 08:11:38,860 Connection   INFO     Using TLS v1.0
2021-07-07 08:11:39,356 Diagnostics  INFO     Creating request message
2021-07-07 08:11:39,356 Diagnostics  INFO     Request message=0001000200000008ffffffff48900061
2021-07-07 08:11:39,356 Diagnostics  INFO     Sending request message
2021-07-07 08:11:39,356 Diagnostics  INFO     Receiving response message
2021-07-07 08:11:39,366 Diagnostics  INFO     Response message=KGRwMApTJ2xlbmd0aCcKcDEKSTQ4CnNTJ3ZlcnNpb24nCnAyCkkxCnNTJ2RhdGEnCnAzClMnXHgwMFx4MDBceDEzXHg4OVx4MDBceDAwXHgwMFx4MDhceDAwXHgwMFx4MDBceDAwXHgwMFx4MDBceDAwXHgwMFx4MDBceDAwXHgxM1x4ODhceDAwXHgwMFx4MDBceDA4XHgwMFx4MDBceDAwXHgwMFx4MDBceDAwXHgwMFx4MDBceDAwXHgwMFx4MWFceDBiXHgwMFx4MDBceDAwXHgwOFx4MDBceDAwXHgwMFx4MDBceDAwXHgwMFx4MDBceDAwJwpwNApzUydtZXNzYWdlVHlwZScKcDUKSTIwNTEKcy4=
2021-07-07 08:11:39,366 Diagnostics  INFO     Streaming info response
2021-07-07 08:11:39,366 Diagnostics  INFO     Connection successful
