### ISSUE TITLE
ModuleNotFoundError: No module named 'six' 

### ISSUE THREAD

**Issue by AVitg** [CiscoSecurity/fp-05-microsoft-sentinel-connector#4]
Hi, 
i am trying to get this pyhton code running on a RHEL 7.9.2009

`./encore.sh foreground
Traceback (most recent call last):
  File "./estreamer/preflight.py", line 33, in <module>
    import estreamer.crossprocesslogging
  File "/scripts/eNcore/fp-05-microsoft-sentinel-connector-main/estreamer/__init__.py", line 26, in <module>
    from estreamer.bookmark import Bookmark
  File "/scripts/eNcore/fp-05-microsoft-sentinel-connector-main/estreamer/bookmark.py", line 23, in <module>
    import estreamer.crossprocesslogging as logging
  File "/scripts/eNcore/fp-05-microsoft-sentinel-connector-main/estreamer/crossprocesslogging/__init__.py", line 85, in <module>
    from estreamer.crossprocesslogging.stdOutClient import StdOutClient
  File "/scripts/eNcore/fp-05-microsoft-sentinel-connector-main/estreamer/crossprocesslogging/stdOutClient.py", line 23, in <module>
    from estreamer.common import convert
  File "/scripts/eNcore/fp-05-microsoft-sentinel-connector-main/estreamer/common/__init__.py", line 19, in <module>
    from estreamer.common.flatdict import Flatdict
  File "/scripts/eNcore/fp-05-microsoft-sentinel-connector-main/estreamer/common/flatdict.py", line 2, in <module>
    import six
ModuleNotFoundError: No module named 'six'
` 

but i got this error,
`yum search python| grep six
python-six.noarch : Python 2 and 3 compatibility utilities`

`yum install python-six
Package python-six-1.9.0-2.el7.noarch already installed and latest version
Nothing to do`

any suggestion is welcome.
Cheers
A

**Comment by cyberpope** [comment]
You need to install python3-six as the connector uses python3 not python2, we had similar issue
