### ISSUE TITLE
Breaking at socket.recv

### ISSUE THREAD

**Issue by rraj1996** [CiscoSecurity/fp-05-microsoft-sentinel-connector#6]
Hi Folks,

Can anyone help me fix the error by looking at the screenshot below? Sorry I won't be able to describe it better since I am not programmer.

![image](https://user-images.githubusercontent.com/47597663/192613012-dd92dd89-ff32-40ea-9718-e3cd7e687316.png)

Also would like to inform you about some changes that I made to the config file 
1) Port was changed to 443 
2) Host was changed to FMC IP

Thanks to you in advance.

Regards

**Comment by rraj1996** [comment]
2022-09-27T15:16:13.651577 Diagnostics  INFO    Checking that configFilepath (estreamer.conf) exists
2022-09-27 15:16:13,669 Diagnostics  INFO     Check certificate
2022-09-27 15:16:13,669 Diagnostics  INFO     Creating connection
2022-09-27 15:16:13,669 Connection   INFO     Connecting to 1xxxx.x6.xx.xx:443
2022-09-27 15:16:13,669 Connection   INFO     Using TLS v1.2
2022-09-27 15:16:13,675 Diagnostics  INFO     Creating request message
2022-09-27 15:16:13,676 Diagnostics  INFO     Request message=b'0001000200000008ffffffff48900061'
2022-09-27 15:16:13,676 Diagnostics  INFO     Sending request message
2022-09-27 15:16:13,676 Diagnostics  INFO     Receiving response message
This is want - 8
Traceback (most recent call last):
  File "/home/ubuntu/fp-05-microsoft-sentinel-connector/estreamer/connection.py", line 150, in __read
    peekBytes = self.socket.recv( want )
  File "/usr/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./estreamer/diagnostics.py", line 169, in main
    diagnostics.execute()
  File "./estreamer/diagnostics.py", line 97, in execute
    response = connection.response()
  File "/home/ubuntu/fp-05-microsoft-sentinel-connector/estreamer/connection.py", line 184, in response
    dataBuffer = self.__read( 8 )
  File "/home/ubuntu/fp-05-microsoft-sentinel-connector/estreamer/connection.py", line 175, in __read
    raise estreamer.TimeoutException('Connection read timeout')
estreamer.exception.TimeoutException: Connection read timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./estreamer/diagnostics.py", line 180, in <module>
    Diagnostics.main()
  File "./estreamer/diagnostics.py", line 172, in main
    logger.error(ex)
  File "/home/ubuntu/fp-05-microsoft-sentinel-connector/estreamer/crossprocesslogging/baseClient.py", line 100, in error
    self.log(logging.ERROR, data)
  File "/home/ubuntu/fp-05-microsoft-sentinel-connector/estreamer/crossprocesslogging/baseClient.py", line 69, in log
    data = self.__serialise( data )
  File "/home/ubuntu/fp-05-microsoft-sentinel-connector/estreamer/crossprocesslogging/baseClient.py", line 35, in __serialise
    message = data.__class__.__name__ + ': ' + data.message
AttributeError: 'TimeoutException' object has no attribute 'message'
